#!/usr/bin/env python3
"""Generate BRACIS v0 import manifest with SHA256 metadata.

Scans data/raw/bracis_v0 and results/raw/bracis_v0 without modifying artifacts.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Iterable

ROOT = Path(__file__).resolve().parents[1]
SCAN_DIRS = [ROOT / "data/raw/bracis_v0", ROOT / "results/raw/bracis_v0"]
MANIFEST_PATH = ROOT / "docs/artifact_manifests/bracis_v0_import_manifest.md"


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(8192), b""):
            h.update(chunk)
    return h.hexdigest()


def iter_artifacts() -> Iterable[Path]:
    for base in SCAN_DIRS:
        if not base.exists():
            continue
        for p in sorted(base.rglob("*")):
            if p.is_file() and p.name != ".DS_Store":
                yield p


def classify(path: Path) -> tuple[str, str, str]:
    # category, purpose, linked group
    if path.name.lower() == "readme.md":
        return (
            "scaffold_metadata",
            "Scaffold placeholder note (not an experimental artifact)",
            "none",
        )
    return (
        "experimental_artifact",
        "Imported BRACIS v0 artifact (purpose pending detailed mapping)",
        "unknown",
    )


def main() -> int:
    rows = []
    for p in iter_artifacts():
        rel = p.relative_to(ROOT)
        category, purpose, group = classify(p)
        rows.append(
            {
                "original": "unknown_or_unavailable_in_current_environment",
                "new": str(rel),
                "ftype": p.suffix.lstrip(".") or "no_ext",
                "size": p.stat().st_size,
                "sha256": sha256_file(p),
                "purpose": purpose,
                "group": group,
                "category": category,
                "immutable": "yes",
            }
        )

    lines = [
        "# BRACIS v0 Import Manifest\n\n",
        "Generated by `python scripts/make_artifact_manifest.py`.\n",
        "Rows are classified as `experimental_artifact`, `scaffold_metadata`, or `unknown`.\n\n",
        "| Original path/source | New repository path | File type | File size (bytes) | SHA256 | Purpose | Linked result group | Category | Immutable |\n",
        "|---|---|---|---:|---|---|---|---|---|\n",
    ]

    if rows:
        for r in rows:
            lines.append(
                f"| {r['original']} | `{r['new']}` | {r['ftype']} | {r['size']} | `{r['sha256']}` | {r['purpose']} | {r['group']} | {r['category']} | {r['immutable']} |\n"
            )
    else:
        lines.append(
            "| none available in current environment | n/a | n/a | 0 | n/a | No BRACIS v0 artifact files were available to import during Task 1/1B. | n/a | unknown | n/a |\n"
        )

    MANIFEST_PATH.write_text("".join(lines), encoding="utf-8")
    exp = sum(1 for r in rows if r["category"] == "experimental_artifact")
    scaff = sum(1 for r in rows if r["category"] == "scaffold_metadata")
    print(f"Manifest written: {MANIFEST_PATH}")
    print(f"Rows listed: {len(rows)}")
    print(f"Experimental artifacts: {exp}")
    print(f"Scaffold metadata files: {scaff}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
