#!/usr/bin/env python3
"""Validate required repository structure for protocol-first scaffold hardening."""

from pathlib import Path

REQUIRED_FILES = [
    "README.md",
    "AGENTS.md",
    "PROTOCOL_LOCK.md",
    "EXPERIMENT_CHANGELOG.md",
    "RESEARCH_LOG.md",
    "requirements.txt",
    "pyproject.toml",
    ".gitignore",
    "CITATION.cff",
    "docs/00_project_scope.md",
    "docs/01_research_questions.md",
    "docs/02_claims_allowed_forbidden.md",
    "docs/03_cct_formal_schema.md",
    "docs/04_metrics_definition.md",
    "docs/05_reproducibility_checklist.md",
    "docs/06_journal_positioning.md",
    "docs/07_desk_reject_artifact_audit.md",
    "docs/08_artifact_recovery_or_reconstruction_decision.md",
    "docs/09_journal_v1_reconstruction_protocol.md",
    "docs/10_journal_v1_operational_contracts.md",
    "docs/11_journal_v1_corpus_plan_and_label_rubric.md",
    "docs/12_journal_v1_main_corpus_generation_readiness.md",
    "docs/13_full_trace_schema_migration_plan.md",
    "docs/16_cct_causal_flow_edge_redesign_spec.md",
    "src/cctdiag/__init__.py",
    "src/cctdiag/schema/__init__.py",
    "src/cctdiag/schema/errors.py",
    "src/cctdiag/schema/validators.py",
    "src/cctdiag/schema/contracts.py",
    "src/cctdiag/schema/full_trace_contracts.py",
    "src/cctdiag/schema/full_trace_validators.py",
    "src/cctdiag/io/__init__.py",
    "src/cctdiag/io/loaders.py",
    "src/cctdiag/io/views.py",
    "src/cctdiag/io/full_trace_views.py",
    "src/cctdiag/cct/__init__.py",
    "src/cctdiag/cct/causal_edges.py",
    "src/cctdiag/features/__init__.py",
    "src/cctdiag/baselines/__init__.py",
    "src/cctdiag/baselines/trivial.py",
    "src/cctdiag/baselines/flat_log.py",
    "src/cctdiag/baselines/spectrum.py",
    "src/cctdiag/diagnosis/__init__.py",
    "src/cctdiag/perturbations/__init__.py",
    "src/cctdiag/metrics/__init__.py",
    "src/cctdiag/metrics/attribution.py",
    "src/cctdiag/metrics/sanity.py",
    "src/cctdiag/stats/__init__.py",
    "src/cctdiag/reporting/__init__.py",
    "src/cctdiag/audit/splits.py",
    "src/cctdiag/audit/integrity.py",
    "src/cctdiag/audit/leakage.py",
    "src/cctdiag/audit/__init__.py",
    "configs/protocol.yaml",
    "configs/metrics.yaml",
    "configs/seeds.yaml",
    "configs/baselines.yaml",
    "configs/ablations.yaml",
    "configs/robustness.yaml",
    "configs/label_rubric.yaml",
    "configs/corpus_plan.yaml",
    "tests/test_placeholder.py",
    "scripts/validate_repo.py",
    "scripts/build_cct_descriptor_augmented_features.py",
    "scripts/prototype_cct_causal_edges_sample.py",
    "scripts/audit_cct_strong_edges_full_corpus.py",
    "scripts/validate_cct_scoring_config_presence.py",
    "scripts/validate_protocol.py",
    "data/raw/.gitkeep",
    "data/interim/.gitkeep",
    "data/interim/journal_v1_pilot/pilot_all_traces.jsonl",
    "data/interim/journal_v1_pilot/pilot_perturbed_traces.jsonl",
    "data/interim/journal_v1_pilot/pilot_clean_traces.jsonl",
    "data/processed/.gitkeep",
    "data/external/.gitkeep",
    "results/raw/.gitkeep",
    "results/tables/.gitkeep",
    "results/figures/.gitkeep",
    "results/reports/.gitkeep",
    "results/reports/bracis_v0_reported_results.md",
    "notebooks/exploratory/.gitkeep",
    "results/raw/bracis_v0/README.md",
    "data/raw/bracis_v0/README.md",
    "tests/test_artifact_import.py",
    "tests/test_contracts.py",
    "tests/fixtures/journal_v1/minimal_invalid_label_reference.json",
    "tests/fixtures/journal_v1/minimal_invalid_trace_missing_field.json",
    "tests/fixtures/journal_v1/minimal_valid_trace.json",
    "tests/fixtures/journal_v1/minimal_corpus_duplicate_trace_id.jsonl",
    "tests/fixtures/journal_v1/minimal_corpus_bad_parent_link.jsonl",
    "tests/fixtures/journal_v1/minimal_corpus_leakage.jsonl",
    "tests/fixtures/journal_v1/minimal_corpus_valid.jsonl",
    "tests/fixtures/full_trace/minimal_valid_full_trace.json",
    "tests/fixtures/full_trace/invalid_missing_steps.json",
    "tests/fixtures/full_trace/invalid_gold_step_not_in_steps.json",
    "tests/fixtures/full_trace/invalid_failure_centered_top_level.json",
    "tests/fixtures/full_trace/invalid_single_candidate_trace.json",
    "tests/test_label_consistency.py",
    "tests/test_schema_validation.py",
    "tests/test_split_safety.py",
    "tests/test_corpus_integrity_audit.py",
    "tests/test_leakage_audit.py",
    "tests/test_corpus_plan.py",
    "tests/test_pilot_corpus_audit.py",
    "tests/test_pilot_corpus_builder.py",
    "tests/test_main_corpus_readiness.py",
    "tests/test_metrics_attribution.py",
    "tests/test_metrics_sanity.py",
    "tests/test_flat_log_baselines.py",
    "tests/test_spectrum_baseline.py",
    "tests/test_prediction_view.py",
    "tests/test_full_trace_schema_validation.py",
    "tests/test_full_trace_prediction_view.py",
    "tests/test_full_trace_pilot_builder.py",
    "tests/test_full_trace_pilot_audit.py",
    "scripts/run_non_cct_baseline_diagnostics.py",
    "scripts/validate_full_trace_schema.py",
    "scripts/validate_full_trace_prediction_view.py",
    "scripts/build_full_trace_pilot_corpus.py",
    "scripts/audit_full_trace_pilot_corpus.py",
    "scripts/run_full_trace_pilot_baseline_sanity.py",
    "results/raw/journal_v1/non_cct_baseline_diagnostics.json",
    "results/reports/journal_v1/non_cct_baseline_diagnostics_report.md",
    "results/reports/journal_v1/evaluation_input_leakage_diagnosis.md",
    "results/reports/journal_v1/evaluation_input_contract.md",
    "results/reports/journal_v1/non_cct_baseline_leakage_correction_plan.md",
    "results/reports/journal_v1/full_trace_schema_blocker_report.md",
    "data/interim/journal_v1_full_trace_pilot/full_trace_pilot_clean.jsonl",
    "data/interim/journal_v1_full_trace_pilot/full_trace_pilot_perturbed.jsonl",
    "data/interim/journal_v1_full_trace_pilot/full_trace_pilot_all.jsonl",
    "data/interim/journal_v1_full_trace_cct/sample_cct_causal_edge_augmented_graphs.jsonl",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_inventory.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_audit_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_semantic_spotcheck.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_generation_risk_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_shortcut_baseline_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_diagnostic_sufficiency_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_candidate_plausibility_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_revision_recommendations.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_semantic_diversity_report.md",
    "results/reports/journal_v1_full_trace_pilot/full_trace_pilot_readiness_gate.md",
    "data/processed/journal_v1_full_trace/main_full_trace_clean.jsonl",
    "data/processed/journal_v1_full_trace/main_full_trace_perturbed.jsonl",
    "data/processed/journal_v1_full_trace/main_full_trace_all.jsonl",
    "results/reports/journal_v1_full_trace/main_full_trace_inventory.md",
    "results/reports/journal_v1_full_trace/main_full_trace_audit_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_label_distribution_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_h6_distribution_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_shortcut_baseline_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_semantic_diversity_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_diagnostic_sufficiency_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_candidate_plausibility_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_generation_risk_report.md",
    "results/reports/journal_v1_full_trace/main_full_trace_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_feature_inventory.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_feature_leakage_audit.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_feature_variance_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_shortcut_risk_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_descriptor_augmented_artifact_size_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_negative_diagnostic_evidence_synthesis.md",
    "results/reports/journal_v1_full_trace_cct/cct_revision_path_decision_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_claim_boundary_update.md",
    "results/reports/journal_v1_full_trace_cct/cct_next_experiment_recommendation.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_flow_edge_redesign_risk_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_flow_edge_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_representation_redesign_claim_boundary.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_inventory.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_leakage_audit.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_template_sensitivity_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_provenance_check.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_template_sensitivity_refinement_plan.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_refined_inventory.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_refined_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_scoring_config_provenance_recovery_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_scoring_config_hash_mismatch_adjudication.md",
    "results/reports/journal_v1_full_trace_cct/cct_task18_reproducibility_boundary.md",
    "results/reports/journal_v1_full_trace_cct/cct_representation_only_status_after_config_blocker.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_robustness_audit.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_sample_rule_limitations.md",
    "results/reports/journal_v1_full_trace_cct/cct_causal_edge_next_readiness_decision.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edge_stress_test_plan.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edge_stress_test_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edge_rule_revision_recommendation.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edge_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edges_full_corpus_inventory.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edges_full_corpus_leakage_audit.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edges_full_corpus_distribution_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edges_full_corpus_template_sensitivity_report.md",
    "results/reports/journal_v1_full_trace_cct/cct_strong_edges_full_corpus_readiness_gate.md",
    "src/cctdiag/cct/redesigned_builder.py",
    "src/cctdiag/cct/redesigned_validation.py",
    "scripts/build_cct_redesigned_graphs.py",
    "docs/artifact_manifests/cct_redesigned_graphs_manifest.md",
    "data/interim/journal_v1_full_trace_cct_redesigned/sample_cct_redesigned_graphs.jsonl",
    "data/interim/journal_v1_full_trace_cct_redesigned/cct_redesigned_graph_inventory.json",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_graph_inventory.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_graph_leakage_audit.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_graph_diversity_report.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_graph_degeneracy_report.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_readiness_gate.md",
    "src/cctdiag/cct/redesigned_features.py",
    "scripts/audit_cct_redesigned_features.py",
    "results/raw/journal_v1_full_trace_cct_redesigned/cct_redesigned_features.json",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_feature_inventory.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_feature_leakage_audit.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_feature_variance_report.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_feature_degeneracy_report.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_redesigned_feature_readiness_gate.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_backbone_decision_synthesis.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_article_claim_reframing.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_next_experiment_or_pivot_plan.md",
    "results/reports/journal_v1_full_trace_cct_redesigned/cct_journal_viability_assessment.md",
    "docs/paper_outline_journal_v1.md",
    "docs/paper_evidence_map_journal_v1.md",
    "docs/paper_claims_matrix_journal_v1.md",
    "docs/paper_contribution_statements_journal_v1.md",
    "docs/paper_results_to_report_journal_v1.md",
    "docs/paper_limitations_and_threats_journal_v1.md",
    "docs/paper_target_journal_positioning_journal_v1.md",
    "paper_draft/title_abstract_intro_v1.md",
    "paper_draft/contribution_block_v1.md",
    "paper_draft/keyword_options_v1.md",
    "paper_draft/editorial_positioning_note_v1.md",
    "tests/test_cct_redesigned_features.py",
    "tests/test_cct_redesigned_features_no_private_leakage.py",
    "tests/test_cct_redesigned_features_artifact_policy.py",
    "results/raw/journal_v1_full_trace/main_full_trace_baseline_sanity.json",
    "results/raw/journal_v1_full_trace/main_full_trace_audit_summary.json",
    "results/raw/journal_v1_full_trace_cct/sample_cct_descriptor_augmented_features.json",
    "results/raw/journal_v1_full_trace_cct/cct_causal_edge_sample_prototype.json",
    "results/raw/journal_v1_full_trace_cct/sample_cct_strong_edges_full_corpus.json",
    "scripts/build_full_trace_main_corpus.py",
    "scripts/audit_full_trace_main_corpus.py",
    "scripts/run_full_trace_main_baseline_sanity.py",
    "tests/test_full_trace_main_builder.py",
    "tests/test_full_trace_main_audit.py",
    "tests/test_full_trace_main_baseline_sanity.py",
    "scripts/run_trivial_baseline_sanity.py",
    "results/raw/journal_v1/trivial_baseline_sanity.json",
    "results/reports/journal_v1/trivial_baseline_sanity_report.md",
    "scripts/make_artifact_manifest.py",
    "scripts/validate_contracts.py",
    "scripts/validate_label_consistency.py",
    "scripts/validate_corpus_schema.py",
    "scripts/validate_corpus_plan.py",
    "scripts/audit_leakage.py",
    "scripts/audit_corpus_integrity.py",
    "scripts/audit_pilot_corpus.py",
    "scripts/build_pilot_corpus.py",
    "scripts/check_main_corpus_readiness.py",
    "results/reports/bracis_v0_artifact_inventory.md",
    "results/reports/journal_v1_pilot/pilot_audit_report.md",
    "results/reports/journal_v1_pilot/pilot_lessons_learned.md",
    "results/reports/journal_v1_pilot/pilot_semantic_audit.md",
    "results/reports/journal_v1_pilot/pilot_corpus_inventory.md",
    "results/reports/journal_v1/main_generation_risk_report.md",
    "results/reports/journal_v1/main_h6_semantic_consistency_audit.md",
    "results/reports/journal_v1/main_h6_label_correction_plan.md",
    "results/reports/journal_v1/main_h6_label_consistency_diagnosis.md",
    "scripts/audit_h6_semantic_consistency.py",
    "scripts/audit_label_position_bias.py",
    "results/reports/journal_v1/main_label_position_bias_report.md",
    "results/reports/journal_v1/main_trivial_baseline_risk_report.md",
    "results/reports/journal_v1/main_label_position_bias_correction_plan.md",
    "results/reports/journal_v1/main_failure_step_revision_plan.md",
    "results/reports/journal_v1/main_failure_step_distribution_after_revision.md",
    "results/reports/journal_v1/main_failure_step_semantic_sanity_check.md",
    "results/reports/journal_v1/final_pre_evaluation_gate_report.md",
    "results/reports/journal_v1/main_label_distribution_report.md",
    "results/reports/journal_v1/main_semantic_spotcheck_report.md",
    "docs/artifact_manifests/journal_v1_main_corpus_manifest.md",
    "docs/artifact_manifests/journal_v1_descriptor_augmented_features_manifest.md",
    "docs/artifact_manifests/cct_strong_edges_full_corpus_manifest.md",
    "scripts/audit_main_corpus_semantics.py",
    "scripts/make_journal_v1_manifest.py",
    "docs/artifact_manifests/bracis_v0_import_manifest.md",
    "docs/artifact_manifests/bracis_v0_missing_artifacts.md",
    "docs/artifact_manifests/bracis_v0_recovery_attempt.md",
]

REQUIRED_DIRS = [
    "docs",
    "docs/artifact_manifests",
    "src",
    "src/cctdiag",
    "src/cctdiag/schema",
    "src/cctdiag/io",
    "src/cctdiag/cct",
    "src/cctdiag/features",
    "src/cctdiag/baselines",
    "src/cctdiag/diagnosis",
    "src/cctdiag/perturbations",
    "src/cctdiag/metrics",
    "src/cctdiag/stats",
    "src/cctdiag/reporting",
    "configs",
    "tests",
    "scripts",
    "data",
    "data/raw",
    "data/raw/bracis_v0",
    "data/interim",
    "data/interim/journal_v1_pilot",
    "data/interim/journal_v1_full_trace_pilot",
    "data/interim/journal_v1_full_trace_cct",
    "data/processed",
    "results/raw/journal_v1_full_trace",
    "results/raw/journal_v1_full_trace_cct",
    "results/reports/journal_v1_full_trace",
    "results/reports/journal_v1_full_trace_cct",
    "data/processed/journal_v1_full_trace",
    "data/external",
    "results",
    "results/raw",
    "results/raw/bracis_v0",
    "results/raw/journal_v1",
    "results/tables",
    "results/figures",
    "results/reports",
    "results/reports/journal_v1_pilot",
    "results/reports/journal_v1",
    "results/reports/journal_v1_full_trace_pilot",
    "notebooks",
    "notebooks/exploratory",
]



AMBIGUOUS_NAMES = [
    "io",
    "schema",
    "metrics",
    "stats",
    "reporting",
    "baselines",
    "diagnosis",
    "perturbations",
    "features",
    "cct",
]

def main() -> int:
    root = Path(__file__).resolve().parents[1]
    missing_files = [p for p in REQUIRED_FILES if not (root / p).is_file()]
    missing_dirs = [p for p in REQUIRED_DIRS if not (root / p).is_dir()]

    ambiguous = []
    for name in AMBIGUOUS_NAMES:
        mod = root / "src" / "cctdiag" / f"{name}.py"
        pkg = root / "src" / "cctdiag" / name
        if mod.exists() and pkg.is_dir():
            ambiguous.append(name)

    print("=== Repository Validation Report ===")
    print(f"Root: {root}")
    print(f"Checked directories: {len(REQUIRED_DIRS)}")
    print(f"Checked files: {len(REQUIRED_FILES)}")

    if missing_dirs:
        print("\nMissing directories:")
        for d in missing_dirs:
            print(f"  - {d}")
    else:
        print("\nDirectories: PASS")

    if missing_files:
        print("\nMissing files:")
        for f in missing_files:
            print(f"  - {f}")
    else:
        print("\nFiles: PASS")

    if ambiguous:
        print("\nAmbiguous module/package names:")
        for name in ambiguous:
            print(f"  - {name}")
    else:
        print("\nAmbiguity check: PASS")

    if missing_dirs or missing_files or ambiguous:
        print("\nFINAL: FAIL")
        return 1

    print("\nFINAL: PASS")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
